### PR TITLE
[WIP] Fix issues with pytorch 1.13 on MacOs

### PR DESCRIPTION
**Pull request by lsickert**
## Description

This PR fixes issues that exist in PyTorch v1.13 on MacOS related to the following issues in PyTorch: [88049](https://github.com/pytorch/pytorch/issues/88049) [88826](https://github.com/pytorch/pytorch/pull/88826)

The current workaround is it to revert to PyTorch 1.12.1 and disable the use of the mps device on MacOS, but the issues should be fully resolved in PyTorch 1.13.1 ([Release Tracker](https://github.com/pytorch/pytorch/issues/89855)) which is scheduled to be GA by Dec 15th.

## Related Issue

[150](https://github.com/inseq-team/inseq/issues/150)

## Type of Change

- [ ] 📚 Examples / docs / tutorials / dependencies update
- [x] 🔧 Bug fix (non-breaking change which fixes an issue)
- [ ] 🥂 Improvement (non-breaking change which improves an existing feature)
- [ ] 🚀 New feature (non-breaking change which adds functionality)
- [ ] 💥 Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🔐 Security fix

## Checklist

- [x] I've read the [`CODE_OF_CONDUCT.md`](https://github.com/inseq-team/inseq/blob/master/CODE_OF_CONDUCT.md) document.
- [x] I've read the [`CONTRIBUTING.md`](https://github.com/inseq-team/inseq/blob/master/CONTRIBUTING.md) guide.
- [x] I've updated the code style using `make codestyle`.
- [ ] I've written tests for all new methods and classes that I created.
- [ ] I've written the docstring in Google format for all the methods and classes that I used.

### CODE REVIEW

**Comment by lsickert** [comment]
@gsarti I updated Pytorch 1.13.1 and the installation issues on macOS are now fully resolved. However, not all of the issues with MPS are fixed by 1.13.1 and some of the tests are still failing. So I left the workaround of hardcoding the device to CPU on MPS devices in the code and added a comment about this. I would suggest merging this branch and closing the associated bug ticket and I will open a new issue to track the remaining issues with MPS as I think there is not much we can currently do until newer PyTorch versions might fix the remaining issues.

**Comment by gsarti** [comment]
Checked the changes, could you justify why setting `python3` instead of 3.8 in the pre-commit config? Apart from that, LGTM!

**Review by gsarti — APPROVED** [review]
Good for merging as temporary MPS fix

**Comment by lsickert** [comment]
> Checked the changes, could you justify why setting `python3` instead of 3.8 in the pre-commit config? Apart from that, LGTM!

Sorry, that was just meant temporarily to make things more comfortable during development as I am usually not on 3.8 anymore and sometimes forget to switch the version between different projects. I can revert it back to 3.8, but since the code will be checked against the different versions on GitHub anyways maybe we could just leave it like that?

**Pull request merged**
